name: gmd
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - pip
  - ca-certificates
  - gdown
  - matplotlib>=3.1.3
  - numpy>=1.22
  - pillow>=9.2.0
  - python>3.9
  - torchmetrics>0.11
  - scikit-learn>=1.0.2
  - scipy>=1.7.3
  - six
  - spacy>=3.3.1
  - tqdm
  - seaborn
  - nvtop
  - conda-forge:
      - ffmpeg
  - pip:
    - pytorch>=2.0
    - pytorch-lightning>=1.9
    - pytorch-cuda>11.6
    - torchaudio
    - torchvision
    - chumpy==0.70
    - smplx==0.1.28
    - blobfile
    - PyYaml
    - tensorboard
    - einops
    - trimesh
    - h5py
    - natsort
    - omegaconf
