#!/bin/bash

#SBATCH --account=digital_human_jobs
#SBATCH --gpus=1
#SBATCH --time=24:00:00
#SBATCH --job-name="DNO generate Adam"

source ~/.bashrc
cd ~/team/
conda activate dno-env-new/
cd Diffusion-Noise-Optimization/

python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person walking with their arms swinging back to front and walking in a general circle"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person is performing a right to left jogging move"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person is walking forward briskly"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="person is walking without their arms swinging"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person walks forward then turns around and walks back"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person slowly walking forward towards something"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person walks slowly forward."
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a step forward then a large step like walking over something then back to normal"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person slowly walks forward with spine slightly hunched forward, turns around to their right and walks forward some more in the other direction, and then turns around to their right and walks forward again"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person is walking but paranoid someone is following them"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="person walks up and then looks around behind him like someone is watching him"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person runs and jumps forward"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a running man hops over something a comes down to a walk"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person raises his right arm and moves his left arm and left hand up and down in a regular fashion"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person is walking casually with their arms slightly swinging"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person casually walks forward and then stops dramatically"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person is jumping from side to side"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person is moving and making gestures as if in a boxing ring"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="person looks to be reaching for something above that they cannot see"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person reaches forward with their right hand and then again reaching lower and then again reaching toward the ground while squatting, then reaching to the their right and down"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person walks is standing still and moving their arms and hands with exaggerated and fluid movements."
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a man raises its right arm and wiggles it and brings it back down."
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a person is jogging forward and looking at the ground"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a man walks forward two steps then bends over to catch his breath and starts running."
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a man squats extraordinarily low then bolts up in an unsatisfactory jump"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a man is walking forward, favoring his left leg and shifting his walk. he is possibly drunk"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a man is pretending to be a chicken. constantly pecking at the ground and waving his arms like a chicken."
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=27 text_prompt="a man is walking and waves his right hand"

python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person walking with their arms swinging back to front and walking in a general circle"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person is performing a right to left jogging move"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person is walking forward briskly"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="person is walking without their arms swinging"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person walks forward then turns around and walks back"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person slowly walking forward towards something"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person walks slowly forward."
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a step forward then a large step like walking over something then back to normal"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person slowly walks forward with spine slightly hunched forward, turns around to their right and walks forward some more in the other direction, and then turns around to their right and walks forward again"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person is walking but paranoid someone is following them"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="person walks up and then looks around behind him like someone is watching him"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person runs and jumps forward"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a running man hops over something a comes down to a walk"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person raises his right arm and moves his left arm and left hand up and down in a regular fashion"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person is walking casually with their arms slightly swinging"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person casually walks forward and then stops dramatically"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person is jumping from side to side"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person is moving and making gestures as if in a boxing ring"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="person looks to be reaching for something above that they cannot see"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person reaches forward with their right hand and then again reaching lower and then again reaching toward the ground while squatting, then reaching to the their right and down"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person walks is standing still and moving their arms and hands with exaggerated and fluid movements."
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a man raises its right arm and wiggles it and brings it back down."
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a person is jogging forward and looking at the ground"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a man walks forward two steps then bends over to catch his breath and starts running."
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a man squats extraordinarily low then bolts up in an unsatisfactory jump"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a man is walking forward, favoring his left leg and shifting his walk. he is possibly drunk"
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a man is pretending to be a chicken. constantly pecking at the ground and waving his arms like a chicken."
python -m dno_optimized.generate config/trajectory_editing_adam.yml experiment="adam-trajectory" seed=29 text_prompt="a man is walking and waves his right hand"

python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person walking with their arms swinging back to front and walking in a general circle"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person is performing a right to left jogging move"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person is walking forward briskly"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="person is walking without their arms swinging"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person walks forward then turns around and walks back"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person slowly walking forward towards something"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person walks slowly forward."
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a step forward then a large step like walking over something then back to normal"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person slowly walks forward with spine slightly hunched forward, turns around to their right and walks forward some more in the other direction, and then turns around to their right and walks forward again"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person is walking but paranoid someone is following them"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="person walks up and then looks around behind him like someone is watching him"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person runs and jumps forward"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a running man hops over something a comes down to a walk"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person raises his right arm and moves his left arm and left hand up and down in a regular fashion"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person is walking casually with their arms slightly swinging"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person casually walks forward and then stops dramatically"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person is jumping from side to side"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person is moving and making gestures as if in a boxing ring"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="person looks to be reaching for something above that they cannot see"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person reaches forward with their right hand and then again reaching lower and then again reaching toward the ground while squatting, then reaching to the their right and down"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person walks is standing still and moving their arms and hands with exaggerated and fluid movements."
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a man raises its right arm and wiggles it and brings it back down."
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a person is jogging forward and looking at the ground"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a man walks forward two steps then bends over to catch his breath and starts running."
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a man squats extraordinarily low then bolts up in an unsatisfactory jump"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a man is walking forward, favoring his left leg and shifting his walk. he is possibly drunk"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a man is pretending to be a chicken. constantly pecking at the ground and waving his arms like a chicken."
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=27 text_prompt="a man is walking and waves his right hand"

python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person walking with their arms swinging back to front and walking in a general circle"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person is performing a right to left jogging move"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person is walking forward briskly"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="person is walking without their arms swinging"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person walks forward then turns around and walks back"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person slowly walking forward towards something"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person walks slowly forward."
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a step forward then a large step like walking over something then back to normal"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person slowly walks forward with spine slightly hunched forward, turns around to their right and walks forward some more in the other direction, and then turns around to their right and walks forward again"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person is walking but paranoid someone is following them"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="person walks up and then looks around behind him like someone is watching him"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person runs and jumps forward"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a running man hops over something a comes down to a walk"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person raises his right arm and moves his left arm and left hand up and down in a regular fashion"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person is walking casually with their arms slightly swinging"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person casually walks forward and then stops dramatically"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person is jumping from side to side"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person is moving and making gestures as if in a boxing ring"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="person looks to be reaching for something above that they cannot see"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person reaches forward with their right hand and then again reaching lower and then again reaching toward the ground while squatting, then reaching to the their right and down"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person walks is standing still and moving their arms and hands with exaggerated and fluid movements."
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a man raises its right arm and wiggles it and brings it back down."
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a person is jogging forward and looking at the ground"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a man walks forward two steps then bends over to catch his breath and starts running."
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a man squats extraordinarily low then bolts up in an unsatisfactory jump"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a man is walking forward, favoring his left leg and shifting his walk. he is possibly drunk"
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a man is pretending to be a chicken. constantly pecking at the ground and waving his arms like a chicken."
python -m dno_optimized.generate config/pose_editing_adam.yml experiment="adam-pose" seed=29 text_prompt="a man is walking and waves his right hand"
