task: trajectory_editing
experiment: controversial_example
text_prompt: a person is jumping
seed: 24
dno:
  num_opt_steps: 50
  optimizer: LBFGS # Adam, SGD, LBFGS, LevenbergMarquardt, ...
  perturb_scale: 0
  lr: 1.0 # LBFGS needs much higher learning rate
  lr_warm_up_steps: 0
  lr_decay_steps: 10 # Set to 0 to disable, -1 to use default (== num_opt_steps)
  decay_first: false
  decorrelate_scale: 0
  lbfgs:
    history_size: 20
    max_iter: 5
    line_search_fn: strong_wolfe # Or "strong_wolfe"
  normalize_gradient: false
  gradient_clip_val: 15.0
extra_callbacks:
  - name: tensorboard
    args:
      every_n_steps: 1
  - name: profiler
