task: pose_editing
experiment: pose_editing
text_prompt: a person is jumping
seed: 20
dno:
  optimizer: Adam
  num_opt_steps: 800
  lr: 0.01
  lr_warm_up_steps: 50
  lr_decay_steps: 500
  decorrelate_scale: 100.0
callbacks:
  - name: tensorboard
    args:
      every_n_steps: 10
