task: trajectory_editing
num_ode_steps: 10
gradient_checkpoint: False
dno:
  num_opt_steps: 800
  optimizer: Adam # Adam, SGD, LBFGS, LevenbergMarquardt, ...
  lr: 5e-2 # Default
extra_callbacks:
  - name: profiler
  - name: generate_video
    args:
      every_n_steps: 5
