task: trajectory_editing
num_ode_steps: 10
gradient_checkpoint: False
experiment: trajectory_editing
dno:
  optimizer: Adam
  num_opt_steps: 800
  lr: 5e-2
extra_callbacks:
  - name: profiler
  - name: early_stopping
    args:
      patience: 200
      min_improvement: 0
      abs_value: 1e-5
