task: trajectory_editing
experiment: "0524_lm_exploration"
num_ode_steps: 10
gradient_checkpoint: False
num_trials: 1
dataloader_num_workers: 2
dno:
  num_opt_steps: 10
  optimizer: LevenbergMarquardt # Adam, SGD, LBFGS, LevenbergMarquardt, ...
  lr: 0.5
  levenbergMarquardt:
    attempts_per_step: 10
extra_callbacks:
  - name: early_stopping
    args:
      patience: 250
      min_improvement: 0
      abs_value: 1e-5
  - name: profiler
  - name: generate_video
    args:
     schedule:
       [
         2,
         4,
         6,
         8,
       ]
