task: trajectory_editing
experiment: "0524_gauss_newton"
num_trials: 1
dataloader_num_workers: 2
dno:
  num_opt_steps: 20
  optimizer: LevenbergMarquardt # Adam, SGD, LBFGS, LevenbergMarquardt, ...
  lr: 0.1
  lr_warm_up_steps: 0 # 5
  lr_decay_steps: 0 # 10
  diff_penalty_scale: 2e-3 # default: 2e-3 for editing tasks (i.e. pose and trajectory editing) and 0 otherwise
  decorrelate_scale: 50 # default 1000 (way too big for LM)
  levenbergMarquardt:
    attempts_per_step: 10
    solve_method: lstsq
    # Setting damping factor to zero gives us Gauss Newton
    damping_strategy:
      starting_value: 0
      min_value: 0
callbacks:
  - name: tensorboard
    args:
      every_n_steps: 1
  - name: early_stopping
    args:
      patience: 50
      min_improvement: 1e-4
      abs_value: 1e-5
  - name: save_top_k
extra_callbacks:
  - name: early_stopping
    args:
      patience: 250
      min_improvement: 0
      abs_value: 1e-5
  - name: profiler
  - name: generate_video
    args:
     schedule:
       [
         2,
         4,
         6,
         8,
         10,
         12,
         14,
         16,
         18
       ]
