task: trajectory_editing

model_path: ./save/mdm_avg_dno/model000500000_avg.pt
#output_dir: ./save/mdm_avg_dno/samples_000500000_avg_seed20_a_person_is_jumping/trajectory_editing_dno
#out_path: ./save/mdm_avg_dno/samples_000500000_avg_seed20_a_person_is_jumping/trajectory_editing_dno

## GENERATE
text_prompt: a person is jumping
motion_length: 6.0
input_text: ''
action_file: ''
action_name: ''
load_from: ''
## BASE
cuda: true
device: 0
seed: 20
#batch_size: 1
# DATA
dataset: humanml
data_dir: ''
# MODEL
arch: trans_enc
emb_trans_dec: false
layers: 8
latent_dim: 512
cond_mask_prob: 0.1
lambda_rcxyz: 0.0
lambda_vel: 0.0
lambda_fc: 0.0
unconstrained: false
# DIFFUSION
noise_schedule: cosine
diffusion_steps: 1000
sigma_small: true

# HARDCODED
num_trials: 3
num_ode_steps: 10
gradient_checkpoint: false
use_ddim: true
max_frames: 196
gen_batch_size: 1
num_samples: 1
num_repetitions: 1
fps: 20
guidance_param: 2.5
# Computed
#gen_frames: 120
#niter: 000500000_avg
#n_frames: 120

## DNO OPTIONS
dno:
  stopping_value: 1e-3
  num_opt_steps: 100
  optimizer: Adam

  ## OPTIMIZER OPTIONS
  lbfgs:
    history_size: 10
